"""
NP-Slicer — Local Web Backend (staged workflow with live status)
===================================================================
Zero-dependency HTTP server that wraps the pipeline stages for the
browser:

  * every stage is a button; a stage only unlocks when the previous
    one succeeded;
  * the EXACT inputs used are echoed back before anything runs, so you
    always know your values were taken;
  * warp mode (auto / shear / top) dropdown; the builder's MODE
    decision + reason are shown on the page, and shear mode shows the
    "PrusaSlicer supports OFF" instruction prominently;
  * stdout of the running stage streams into the page (poll /api/status);
  * the sliced G-code is UPLOADED through the page, warped STL / final
    G-code are DOWNLOAD buttons;
  * verification ends in a big PASS / FAIL banner.

Run from the project root:
    python npslicer/server.py
then open  http://localhost:5003
"""

import json
import os
import subprocess
import sys
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse

SRC_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(SRC_DIR)                  # repo root
OUT_DIR = os.path.join(BASE_DIR, "outputs")
STL_DIRS = [os.path.join(BASE_DIR, "inputs", "stls"),
            os.path.join(BASE_DIR, "inputs")]
PORT = 5003

os.makedirs(OUT_DIR, exist_ok=True)

JOB = {
    "stage": None,        # 1..4 while running / last run
    "running": False,
    "ok": None,           # True/False once finished
    "log": [],
    "params": {},         # echoed inputs of the last launch
    "done": {},           # {"1": true, ...} per selected part
    "part": None,         # current stem
}
LOCK = threading.Lock()


def stem_of(stl_name):
    return os.path.splitext(os.path.basename(stl_name))[0].replace(" ", "_")


def list_stls():
    out = []
    for d in STL_DIRS:
        if os.path.isdir(d):
            for f in sorted(os.listdir(d)):
                if f.lower().endswith(".stl"):
                    out.append({"name": f,
                                "path": os.path.join(d, f),
                                "dir": os.path.relpath(d, BASE_DIR)})
    return out


DEFAULT_MK4 = {
    "name": "Prusa MK4 (Nextruder, 0.4 nozzle)",
    "bed_x": 250.0, "bed_y": 210.0, "origin": "corner",
    "nozzle_diameter": 0.4, "filament_diameter": 1.75,
    "nozzle_cone_angle_deg": 30.0, "tip_land_radius": 0.50,
    "gouge_tol_mm": 0.15, "nonplanar_clearance_h": 4.0,
    "shroud_radius": 8.0,
    "head_clearance_h": 10.0, "head_radius": 35.0,
    "theta_target_default": 20.0,
    "_comment": "auto-regenerated by server.py (original was "
                "missing/unreadable) — SPECULATIVE values, measure the "
                "toolhead and edit!",
}


def list_profiles():
    """Read npslicer/profiles/*.json. Never silently returns nothing: parse
    errors are reported to the page, and if no profile is readable at
    all (e.g. OneDrive served a truncated file) a default prusa_mk4 is
    regenerated on disk so the workflow is never blocked."""
    pdir = os.path.join(SRC_DIR, "profiles")
    os.makedirs(pdir, exist_ok=True)
    out, errors = [], []
    for f in sorted(os.listdir(pdir)):
        if not f.endswith(".json"):
            continue
        try:
            with open(pdir + os.sep + f, encoding="utf-8-sig") as fh:
                p = json.load(fh)
            out.append({"name": f[:-5],
                        "label": p.get("name", f[:-5]),
                        "cone": p.get("nozzle_cone_angle_deg"),
                        "tip_r": p.get("tip_land_radius"),
                        "clearance": p.get("nonplanar_clearance_h")})
        except Exception as e:
            errors.append(f"{f}: {e}")
    if not out:
        fp = os.path.join(pdir, "prusa_mk4.json")
        with open(fp, "w") as fh:
            json.dump(DEFAULT_MK4, fh, indent=2)
        errors.append("no readable profile found -> regenerated a "
                      "default prusa_mk4.json (speculative values!)")
        out.append({"name": "prusa_mk4", "label": DEFAULT_MK4["name"],
                    "cone": 30.0, "tip_r": 0.5, "clearance": 4.0})
    return out, errors


def launch(stage, cmd, params):
    """Run one stage in a background thread, streaming stdout to JOB."""
    with LOCK:
        if JOB["running"]:
            return False
        JOB.update(stage=stage, running=True, ok=None, params=params)
        JOB["log"] = [f"$ {' '.join(cmd)}", ""]

    def work():
        try:
            proc = subprocess.Popen(
                [sys.executable, "-u"] + cmd, cwd=BASE_DIR,
                stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, errors="replace")
            for line in proc.stdout:
                with LOCK:
                    JOB["log"].append(line.rstrip("\n"))
            rc = proc.wait()
        except Exception as e:
            with LOCK:
                JOB["log"].append(f"SERVER ERROR: {e}")
                JOB.update(running=False, ok=False)
            return
        with LOCK:
            JOB["ok"] = (rc == 0)
            JOB["running"] = False
            JOB["log"].append("")
            JOB["log"].append(f"--- stage {stage} "
                              f"{'FINISHED OK' if rc == 0 else 'FAILED'} "
                              f"(exit {rc}) ---")
            if rc == 0:
                JOB["done"][str(stage)] = True
                # a rerun of an earlier stage invalidates later ones
                for later in range(stage + 1, 5):
                    JOB["done"].pop(str(later), None)

    threading.Thread(target=work, daemon=True).start()
    return True


def artifacts(part):
    """Which per-part files exist right now (for buttons/links)."""
    if not part:
        return {}
    names = {
        "field": f"{part}_field.npz",
        "preview": f"{part}_field.png",
        "warped": f"{part}_warped.stl",
        "uploaded": f"{part}_uploaded.gcode",
        "final": f"{part}_final.gcode",
    }
    return {k: v for k, v in names.items()
            if os.path.exists(os.path.join(OUT_DIR, v))}


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):                     # silence per-request spam
        pass

    def _send(self, code, body, ctype="application/json"):
        if isinstance(body, (dict, list)):
            body = json.dumps(body).encode()
        elif isinstance(body, str):
            body = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    # ---------------- GET ----------------
    def do_GET(self):
        u = urlparse(self.path)
        q = {k: v[0] for k, v in parse_qs(u.query).items()}
        if u.path in ("/", "/index.html"):
            page = os.path.join(SRC_DIR, "webpage.html")
            with open(page, encoding="utf-8") as f:
                self._send(200, f.read(), "text/html; charset=utf-8")
        elif u.path == "/api/meta":
            profiles, perrors = list_profiles()
            self._send(200, {"stls": [
                {"name": s["name"], "dir": s["dir"]} for s in list_stls()],
                "profiles": profiles, "profile_errors": perrors})
        elif u.path == "/api/status":
            with LOCK:
                st = {k: JOB[k] for k in
                      ("stage", "running", "ok", "params", "done", "part")}
                st["log"] = JOB["log"][-400:]
            st["artifacts"] = artifacts(st["part"])
            self._send(200, st)
        elif u.path == "/api/download":
            name = os.path.basename(q.get("f", ""))
            fp = os.path.join(OUT_DIR, name)
            if not os.path.exists(fp):
                self._send(404, {"error": f"{name} not found"})
                return
            with open(fp, "rb") as f:
                data = f.read()
            ctype = ("image/png" if name.endswith(".png")
                     else "application/octet-stream")
            self.send_response(200)
            self.send_header("Content-Type", ctype)
            if not name.endswith(".png"):
                self.send_header("Content-Disposition",
                                 f'attachment; filename="{name}"')
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)
        else:
            self._send(404, {"error": "unknown path"})

    # ---------------- POST ----------------
    def do_POST(self):
        u = urlparse(self.path)
        n = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(n) if n else b""
        if u.path == "/api/select":                 # choose part (stem)
            data = json.loads(body or b"{}")
            stl = data.get("stl", "")
            match = next((s for s in list_stls() if s["name"] == stl), None)
            if not match:
                self._send(400, {"error": f"STL {stl!r} not found"})
                return
            with LOCK:
                JOB["part"] = stem_of(stl)
                JOB["done"] = {}
                # stages already on disk count as done for convenience
                art = artifacts(JOB["part"])
                if "field" in art:
                    JOB["done"]["1"] = True
                if "warped" in art:
                    JOB["done"]["2"] = True
                if "final" in art:
                    JOB["done"]["3"] = True
            self._send(200, {"part": JOB["part"], "stl_path": match["path"],
                             "resumed": JOB["done"]})
        elif u.path == "/api/run":
            data = json.loads(body or b"{}")
            stage = int(data.get("stage", 0))
            stl = data.get("stl", "")
            match = next((s for s in list_stls() if s["name"] == stl), None)
            if not match:
                self._send(400, {"error": f"STL {stl!r} not found"})
                return
            part = stem_of(stl)
            field = os.path.join("outputs",f"{part}_field.npz")
            prof = data.get("printer", "prusa_mk4")
            params = {"stl": stl, "printer": prof}
            if stage == 1:
                cmd = [os.path.join("npslicer", "1_build_field.py"),
                       "--stl", match["path"], "--printer", prof,
                       "--outdir", "outputs"]
                for k in ("mode", "theta_target", "clearance",
                          "blend_factor", "grid_step", "max_slope"):
                    v = str(data.get(k, "")).strip()
                    if v:
                        cmd += [f"--{k}", v]
                        params[k] = v
            elif stage == 2:
                cmd = [os.path.join("npslicer", "2_warp_stl.py"),
                       "--field", field, "--stl", match["path"]]
            elif stage == 3:
                up = os.path.join(OUT_DIR, f"{part}_uploaded.gcode")
                if not os.path.exists(up):
                    self._send(400, {"error": "upload the sliced G-code "
                                              "first (stage 3 box)"})
                    return
                cmd = [os.path.join("npslicer", "3_unwarp_gcode.py"),
                       "--field", field, "--gcode", up]
                if str(data.get("supports", "")).strip() == "off":
                    cmd += ["--supports", "off"]
                    params["supports"] = "off"
                params["gcode"] = os.path.basename(up)
            elif stage == 4:
                fin = os.path.join("outputs",f"{part}_final.gcode")
                cmd = [os.path.join("npslicer", "4_verify_gcode.py"),
                       "--gcode", fin, "--field", field,
                       "--printer", prof]
                params["gcode"] = f"{part}_final.gcode"
            else:
                self._send(400, {"error": "bad stage"})
                return
            with LOCK:
                JOB["part"] = part
            if launch(stage, cmd, params):
                self._send(200, {"started": True, "stage": stage,
                                 "inputs_received": params})
            else:
                self._send(409, {"error": "another stage is running"})
        elif u.path == "/api/upload_stl":
            q = {k: v[0] for k, v in parse_qs(u.query).items()}
            name = os.path.basename(q.get("name", "upload.stl"))
            if not name.lower().endswith(".stl"):
                name += ".stl"
            name = name.replace(" ", "_")
            if len(body) < 84:                    # smaller than any STL
                self._send(400, {"error": "file too small to be an STL"})
                return
            dest_dir = STL_DIRS[0]
            os.makedirs(dest_dir, exist_ok=True)
            fp = os.path.join(dest_dir, name)
            with open(fp, "wb") as f:
                f.write(body)
            # sanity: can trimesh read it?
            try:
                import trimesh
                m = trimesh.load(fp, force="mesh")
                info = {"faces": int(len(m.faces)),
                        "size_mm": [round(float(x), 1)
                                    for x in (m.bounds[1] - m.bounds[0])]}
            except Exception as e:
                os.remove(fp)
                self._send(400, {"error": f"not a readable STL: {e}"})
                return
            self._send(200, {"saved": name, **info})
        elif u.path == "/api/upload":
            part = parse_qs(urlparse(self.path).query).get(
                "part", [None])[0]
            if not part:
                self._send(400, {"error": "no part selected"})
                return
            txt = body.decode("utf-8", errors="replace")
            if "G1" not in txt:
                self._send(400, {"error": "that does not look like "
                                          "G-code (no G1 moves)"})
                return
            fp = os.path.join(OUT_DIR, f"{part}_uploaded.gcode")
            with open(fp, "w", encoding="utf-8") as f:
                f.write(txt)
            n_lines = txt.count("\n") + 1
            layers = txt.count(";LAYER_CHANGE")
            rel_e = "use_relative_e_distances = 1" in txt
            sup_gc = txt.count(";TYPE:Support")
            self._send(200, {"saved": os.path.basename(fp),
                             "lines": n_lines, "layers": layers,
                             "relative_e_detected": rel_e,
                             "support_gcode_lines": sup_gc})
        else:
            self._send(404, {"error": "unknown path"})


def main():
    srv = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    print(f"NP-Slicer web UI ready:  http://localhost:{PORT}")
    print(f"(project root: {BASE_DIR})")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")


if __name__ == "__main__":
    main()
